# Generated by Django 3.0.6 on 2020-05-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'アイテム', 'verbose_name_plural': 'アイテム'},
        ),
    ]
